# Spring Profile
# active? ??? ??? ??
# ???? ?? ? application-{active}.yml ??? ??? ??
# ????? prd         dev ?? ===== ?? ???? ? ????
spring:
  profiles:
    active: prd

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.cqrs.product.query.dto


#  spring:
#    datasource:
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://{ip}:{port}/{database}
#      username: {user}
#      password: {passward}
#
#  image:
#    image-dir: {??? ?? ?? ??}
#    image-url: {??? ?? ?? URL}