spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cqrs
    username: swcamp
    password: swcamp
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.springsecurity.query.dto

# JWT
jwt:
  secret: /TX6txOQJw4rDYj82onjCbwfZYEQpod3MA9L5mRMbhyG4laOFt1/asEEdUNFkv+EE47eQiB/LdTvLdsryc3RIQ==
  expiration: 1800000 # 30? (accessToken ?? ??)
  refresh-expiration: 604800000 # 1?? (refreshToken ?? ??)



