springdoc:
  # Swagger? ??? ?? API? ??? ??? ??
  packages-to-scan: com.wjdqudwls.restapi.section05
  # consumes : Swagger? ????? ???? "??"? "Content-Type"? ??
  # produces : Swagger? ????? ???? "??"? "Content-Type"? ??
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8