spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cqrs
    username: swcamp
    password: swcamp
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.wjdqudwls.springsecurity.query.dto


# JWT

jwt:
  secret: va6+2wo7i3CEdvYIRjau7/o1IzxyiHWMsS84JUGstZCmlLKOtra6AYUU2QWDc/6cr/w5+Votu4DB7OEZx8qVpg==
  expiration: 1800000 # 30? (accessToken ?? ??)
  refresh-expiration: 604800000 # 30? (refreshToken ?? ??)



